// <auto-generated />
using System;
using DriftDNS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DriftDNS.Infrastructure.Migrations
{
    [DbContext(typeof(DriftDnsDbContext))]
    [Migration("20260317070536_AddAppSettings")]
    partial class AddAppSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("DriftDNS.Core.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("DriftDNS.Core.Models.DnsEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TTL")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderAccountId");

                    b.ToTable("DnsEndpoints");
                });

            modelBuilder.Entity("DriftDNS.Core.Models.ProviderAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedCredentials")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProviderAccounts");
                });

            modelBuilder.Entity("DriftDNS.Core.Models.SyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldIp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId");

                    b.ToTable("SyncLogs");
                });

            modelBuilder.Entity("DriftDNS.Core.Models.SyncState", b =>
                {
                    b.Property<Guid>("EndpointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastAppliedIp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCheckAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastKnownPublicIp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("TEXT");

                    b.HasKey("EndpointId");

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("DriftDNS.Core.Models.DnsEndpoint", b =>
                {
                    b.HasOne("DriftDNS.Core.Models.ProviderAccount", "ProviderAccount")
                        .WithMany("DnsEndpoints")
                        .HasForeignKey("ProviderAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProviderAccount");
                });

            modelBuilder.Entity("DriftDNS.Core.Models.SyncLog", b =>
                {
                    b.HasOne("DriftDNS.Core.Models.DnsEndpoint", "Endpoint")
                        .WithMany("SyncLogs")
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("DriftDNS.Core.Models.SyncState", b =>
                {
                    b.HasOne("DriftDNS.Core.Models.DnsEndpoint", "Endpoint")
                        .WithOne("SyncState")
                        .HasForeignKey("DriftDNS.Core.Models.SyncState", "EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("DriftDNS.Core.Models.DnsEndpoint", b =>
                {
                    b.Navigation("SyncLogs");

                    b.Navigation("SyncState");
                });

            modelBuilder.Entity("DriftDNS.Core.Models.ProviderAccount", b =>
                {
                    b.Navigation("DnsEndpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
